export const STORAGE_KEYS = Object.freeze({
  theme: 'pisper-theme',
  chatMode: 'pisper-chat-mode',
  activeSession: 'pisper-active-session',
  tiledSessions: 'pisper-tiled-sessions',
  chatDockLayout: 'pisper-chat-dock-layout-v1',
  sessionOpenRequest: 'pisper-session-open-request',
  sessionCreateRequest: 'pisper-session-create-request',
  sessionMessageTarget: 'pisper-session-message-target',
  webPreviewRequest: 'pisper-web-preview-request',
  language: 'pisper-language',
  sidebarCollapsed: 'pisper-sidebar-collapsed',
  density: 'pisper-density',
  terminalPanel: 'pisper-terminal-panel',
  sponsorDismissals: 'pisper-sponsor-dismissals',
} as const)
