[package]
name = "pisper-mobile-device-plugin"
version = "0.1.0"
edition = "2021"
links = "pisper-mobile-device-plugin"
publish = false

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = "2"
thiserror = "2"

[target.'cfg(target_os = "ios")'.dependencies]
tauri = { version = "2", features = ["wry"] }
