// 内置工具目录：Pi 引擎自带工具的元数据（风险等级/能力/来源），
// 供工具管理界面与权限审批展示。
export const BUILTIN_TOOL_CATALOG = [
  {
    id: 'read',
    name: 'Read',
    category: 'filesystem',
    risk: 'low',
    description: 'Read text, code, and image files in the workspace.',
    scope: 'Current chat workspace',
    capability: 'Read file contents without modifying files',
    source: 'builtin',
  },
  {
    id: 'ls',
    name: 'List',
    category: 'filesystem',
    risk: 'low',
    description: 'List directory structures and basic file information.',
    scope: 'Current chat workspace',
    capability: 'Browse directories without reading file contents',
    source: 'builtin',
  },
  {
    id: 'grep',
    name: 'Grep',
    category: 'search',
    risk: 'low',
    description: 'Run full-text and regular-expression searches across project files.',
    scope: 'Current chat workspace',
    capability: 'Search text without modifying files',
    source: 'builtin',
  },
  {
    id: 'find',
    name: 'Find',
    category: 'search',
    risk: 'low',
    description: 'Find project files by name and pattern.',
    scope: 'Current chat workspace',
    capability: 'Find paths without modifying files',
    source: 'builtin',
  },
  {
    id: 'edit',
    name: 'Edit',
    category: 'filesystem',
    risk: 'high',
    description: 'Apply precise local edits to existing files.',
    scope: 'Current chat workspace',
    capability: 'Modify existing files and produce diffs',
    source: 'builtin',
  },
  {
    id: 'write',
    name: 'Write',
    category: 'filesystem',
    risk: 'high',
    description: 'Create new files or overwrite file contents.',
    scope: 'Current chat workspace',
    capability: 'Create and overwrite files',
    source: 'builtin',
  },
  {
    id: 'bash',
    name: 'Shell',
    category: 'terminal',
    risk: 'high',
    description: 'Run terminal commands as the current operating-system user.',
    scope: 'Current operating-system user',
    capability: 'Run commands, builds, and tests',
    source: 'builtin',
  },
]

export const TOOL_PRESETS = {
  'read-only': [
    'read',
    'grep',
    'find',
    'ls',
    'web_search',
    'browser_automation',
    'memory_search',
    'memory_remember',
    'mcp_list',
    'mcp_manage',
  ],
  workspace: [
    'read',
    'grep',
    'find',
    'ls',
    'edit',
    'write',
    'skill_create',
    'web_search',
    'browser_automation',
    'memory_search',
    'memory_remember',
    'mcp_list',
    'mcp_manage',
  ],
  full: [
    'read',
    'grep',
    'find',
    'ls',
    'edit',
    'write',
    'bash',
    'skill_create',
    'plugin_create',
    'web_search',
    'browser_automation',
    'generate_visual',
    'memory_search',
    'memory_remember',
    'mcp_list',
    'mcp_manage',
  ],
}
